kind: BuildConfig
apiVersion: v1
metadata:
  name: cloud-gateway-pipeline
spec:
  type: JenkinsPipeline
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
          stage 'build'
          openshiftBuild(buildConfig: 'cloud-gateway', showBuildLogs: 'true')
          stage 'deploy'
          openshiftDeploy(deploymentConfig: 'cloud-gateway')
        }
